name: the_chess_master
description: Gonna get exciting i swear
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chess : ^0.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/BlackKing.png
    - assets/BlackKnight.png
    - assets/BlackBishop.png
    - assets/BlackQueen.png
    - assets/BlackPawn.png
    - assets/BlackRook.png
    - assets/WhiteKing.png
    - assets/WhiteKnight.png
    - assets/WhiteBishop.png
    - assets/WhiteQueen.png
    - assets/WhiteRook.png
    - assets/WhitePawn.png
    - assets/Ring.png
  fonts:
    - family: Magra
      fonts:
        - asset: fonts/Magra-Regular.ttf
        - asset: fonts/Magra-Bold.ttf
          weight: 700




